/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vin
 */
public class feedbackPenyakit extends javax.swing.JFrame {

    /**
     * Creates new form feedbackPenyakit
     */
    public feedbackPenyakit() {
        initComponents();
        this.setLocationRelativeTo(this);
        tb_penyakit.changeSelection(0, 0, true, false);
    }

    public int getSelectedRow() {
        return tb_penyakit.getSelectedRow();
    }

    public void setTable(DefaultTableModel table) {
        this.tb_penyakit.setModel(table);
    }

    public JTable getTablePenyakit() {
        return tb_penyakit;
    }

    public String getPenyakit() {
        return penyakit.getText();
    }

    public String getVaksin() {
        return vaksin.getText();
    }

    public void setPenyakit(String penyakit) {
        this.penyakit.setText(penyakit);
    }

    public void setVaksin(String vaksin) {
        this.vaksin.setText(vaksin);
    }

    public void text(boolean status) {
        this.penyakit.setEnabled(status);
        this.vaksin.setEnabled(status);
    }

    public void button(boolean status) {
        this.btn_submit.setEnabled(status);
        this.btn_kembali.setEnabled(status);
    }

    public void addSubmitListener(ActionListener e) {
        this.btn_submit.addActionListener(e);
    }

    public void addBackListener(ActionListener e) {
        this.btn_kembali.addActionListener(e);
    }

    public void buttonsave(boolean status) {
        this.btn_submit.setEnabled(status);
    }

    public void buttonback(boolean status) {
        this.btn_kembali.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        penyakit = new javax.swing.JTextField();
        vaksin = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_penyakit = new javax.swing.JTable();
        btn_kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1101, 668));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Feedback Penyakit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 360, 47));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Penyakit            : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vaksin                       :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 136, 24));

        penyakit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(penyakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 213, 31));

        vaksin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(vaksin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 213, 35));

        btn_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/save.png"))); // NOI18N
        btn_submit.setBorder(null);
        btn_submit.setBorderPainted(false);
        btn_submit.setContentAreaFilled(false);
        getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 206, 96, 40));

        tb_penyakit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_penyakit);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 280, 700, 227));

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/keluar.png"))); // NOI18N
        btn_kembali.setBorder(null);
        btn_kembali.setBorderPainted(false);
        btn_kembali.setContentAreaFilled(false);
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 160, 43));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/backgrond.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feedbackPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feedbackPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feedbackPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feedbackPenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedbackPenyakit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField penyakit;
    private javax.swing.JTable tb_penyakit;
    private javax.swing.JTextField vaksin;
    // End of variables declaration//GEN-END:variables
}
