/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vin
 */
public class feedbackAdmin extends javax.swing.JFrame {

    /**
     * Creates new form feedbackAdmin
     */
    public feedbackAdmin() {
        initComponents();
        this.setLocationRelativeTo(this);
        tb_penyakit.changeSelection(0, 0, true, false);
    }

    public int getSelectedRow() {
        return tb_penyakit.getSelectedRow();
    }

    public void setTable(DefaultTableModel table) {
        this.tb_penyakit.setModel(table);
    }

    public JTable getTb_penyakit() {
        return tb_penyakit;
    }
       
    public void button(boolean status) {
        this.btn_setuju.setEnabled(status);
        this.btn_tolak.setEnabled(status);
        this.btn_kembali.setEnabled(status);

    }

    public void addSetujuListener(ActionListener e) {
        this.btn_setuju.addActionListener(e);
    }

    public void addTolakListener(ActionListener e) {
        this.btn_tolak.addActionListener(e);
    }

    public void addBackListener(ActionListener e) {
        this.btn_kembali.addActionListener(e);
    }

    public void buttonsetuju(boolean status) {
        this.btn_setuju.setEnabled(status);
    }
    public void buttontolak(boolean status) {
        this.btn_tolak.setEnabled(status);
    }

    public void buttonback(boolean status) {
        this.btn_kembali.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_penyakit = new javax.swing.JTable();
        btn_setuju = new javax.swing.JButton();
        btn_tolak = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1101, 668));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FEEDBACK PENYAKIT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 420, 53));

        tb_penyakit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_penyakit);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 570, 330));

        btn_setuju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/s7.png"))); // NOI18N
        btn_setuju.setBorder(null);
        btn_setuju.setBorderPainted(false);
        btn_setuju.setContentAreaFilled(false);
        getContentPane().add(btn_setuju, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 100, 50));

        btn_tolak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/tolak.png"))); // NOI18N
        btn_tolak.setBorder(null);
        btn_tolak.setBorderPainted(false);
        btn_tolak.setContentAreaFilled(false);
        getContentPane().add(btn_tolak, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 90, -1));

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/keluar.png"))); // NOI18N
        btn_kembali.setBorder(null);
        btn_kembali.setBorderPainted(false);
        btn_kembali.setContentAreaFilled(false);
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 590, 170, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar3/backgrond.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feedbackAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feedbackAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feedbackAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feedbackAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedbackAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_setuju;
    private javax.swing.JButton btn_tolak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_penyakit;
    // End of variables declaration//GEN-END:variables
}
