/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author InSearchOfIncredible
 */
public class homePetani extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public homePetani() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public void addJadwalPupukListener(ActionListener listener) {
        btn_jadwal.addActionListener(listener);
    }

    public void addPupukListener(ActionListener listener) {
        btn_pupuk.addActionListener(listener);
    }

    public void addBibitListener(ActionListener listener) {
        btn_bibit.addActionListener(listener);
    }

    public void addPenyakitListener(ActionListener listener) {
        btn_penyakit.addActionListener(listener);
    }

    public void addLaporanListener(ActionListener listener) {
        btn_laporan.addActionListener(listener);
    }

    public void logoutListener(ActionListener listener) {
        btn_logout.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_laporan = new javax.swing.JButton();
        btn_jadwal = new javax.swing.JButton();
        btn_pupuk = new javax.swing.JButton();
        btn_bibit = new javax.swing.JButton();
        btn_penyakit = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lap panen.png"))); // NOI18N
        btn_laporan.setBorder(null);
        btn_laporan.setBorderPainted(false);
        btn_laporan.setContentAreaFilled(false);
        getContentPane().add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 455, 190, 210));

        btn_jadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jadwal pupuk.png"))); // NOI18N
        btn_jadwal.setBorder(null);
        btn_jadwal.setBorderPainted(false);
        btn_jadwal.setContentAreaFilled(false);
        getContentPane().add(btn_jadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        btn_pupuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/spk.png"))); // NOI18N
        btn_pupuk.setBorder(null);
        btn_pupuk.setBorderPainted(false);
        btn_pupuk.setContentAreaFilled(false);
        getContentPane().add(btn_pupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        btn_bibit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jadwal bibit.png"))); // NOI18N
        btn_bibit.setBorder(null);
        btn_bibit.setBorderPainted(false);
        btn_bibit.setContentAreaFilled(false);
        getContentPane().add(btn_bibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, -1, -1));

        btn_penyakit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/penyakit.png"))); // NOI18N
        btn_penyakit.setBorder(null);
        btn_penyakit.setBorderPainted(false);
        btn_penyakit.setContentAreaFilled(false);
        getContentPane().add(btn_penyakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, -1, -1));

        btn_logout.setText("LOGOUT");
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 560, 100, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home petani 2.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1266, 668));
        jLabel1.setMinimumSize(new java.awt.Dimension(1266, 668));
        jLabel1.setPreferredSize(new java.awt.Dimension(1266, 668));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePetani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bibit;
    private javax.swing.JButton btn_jadwal;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_penyakit;
    private javax.swing.JButton btn_pupuk;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
