/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author InSearchOfIncredible
 */
public class lapPanenPetani extends javax.swing.JFrame {

    /**
     * Creates new form lapPanenPetani
     */
    public lapPanenPetani() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JTextField getPetani() {
        return petani;
    }

    public JTextField getLuas() {
        return luas;
    }

    public JTextField getJumlah() {
        return jumlah;
    }

    public JTable getTable() {
        return tb_panen;
    }

    public void addSimpanListener(ActionListener listener) {
        btn_save.addActionListener(listener);
    }

    public void addHapusListener(ActionListener listener) {
        btn_delete.addActionListener(listener);
    }

    public void backListener(ActionListener listener) {
        btn_kembali.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        jumlah = new javax.swing.JTextField();
        luas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_panen = new javax.swing.JTable();
        petani = new javax.swing.JTextField();
        btn_kembali = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Black Diamonds Personal Use", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Laporan Panen");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 400, 90));

        btn_save.setText("SAVE");
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 90, 40));

        jumlah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 210, 40));

        luas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 210, 40));

        tb_panen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_panen);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 1000, 160));

        petani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(petani, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 210, 40));

        btn_kembali.setText("KEMBALI");
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 120, 40));

        btn_delete.setText("DELETE");
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lap panen petani.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lapPanenPetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lapPanenPetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lapPanenPetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lapPanenPetani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lapPanenPetani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField luas;
    private javax.swing.JTextField petani;
    private javax.swing.JTable tb_panen;
    // End of variables declaration//GEN-END:variables
}
