/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author InSearchOfIncredible
 */
public class pendaftaran extends javax.swing.JFrame {

    /**
     * Creates new form pendaftaran
     */
    public pendaftaran() {
        initComponents();
        this.setLocationRelativeTo(this);
        tb_user.changeSelection(0, 0, true, false);
    }

    public int getSelectedRow() {
        return tb_user.getSelectedRow();
    }

    public void setTable(DefaultTableModel table) {
        this.tb_user.setModel(table);
    }

    public String getValueAt(int baris, int kolom) {
        return tb_user.getValueAt(baris, kolom).toString();
    }

    public String getId() {
        return id.getText();
    }

    public void setId(String id) {
        this.id.setText(id);
    }

    public String getNamaDepan() {
        return namadepan.getText();
    }

    public String getNamaBelakang() {
        return namabelakang.getText();
    }

    public String getAlamat() {
        return alamat.getText();
    }

    public String getNoTelp() {
        return no_telp.getText();
    }

    public String getUsername() {
        return email.getText();
    }

    public String getPassword() {
        return password.getText();
    }

    public String getKode() {
        return kode_pos.getText();
    }

    public String getStatus() {
        return status.getSelectedItem().toString();
    }

    public String getJK() {
        return jenis_kelamin.getSelectedItem().toString();
    }

    public void setNamaDepan(String isi) {
        this.namadepan.setText(isi);
    }

    public void setNamaBelakang(String isi) {
        this.namabelakang.setText(isi);
    }

    public void setAlamat(String isi) {
        this.alamat.setText(isi);
    }

    public void setKode(String isi) {
        this.kode_pos.setText(isi);
    }

    public void setNoTelp(String isi) {
        this.no_telp.setText(isi);
    }

    public void setPassword(String isi) {
        this.password.setText(isi);
    }

    public void setStatus(int status) {
        this.status.setSelectedIndex(status);
    }

    public void setJK(int status) {
        this.jenis_kelamin.setSelectedIndex(status);
    }

    public void setUsername(String isi) {
        this.email.setText(isi);
    }

    public void text(boolean status) {
        this.namadepan.setEnabled(status);
        this.namabelakang.setEnabled(status);
        this.jenis_kelamin.setEnabled(status);
        this.status.setEnabled(status);
        this.email.setEnabled(status);
        this.alamat.setEnabled(status);
        this.kode_pos.setEnabled(status);
        this.no_telp.setEnabled(status);
        this.password.setEnabled(status);
    }

    public void button(boolean status) {
        this.btn_save.setEnabled(status);
        this.btn_edit.setEnabled(status);
        this.btn_update.setEnabled(status);
        this.btn_delete.setEnabled(status);
        this.btn_back.setEnabled(status);
    }

    public void addSaveListener(ActionListener e) {
        this.btn_save.addActionListener(e);
    }

    public void addDeleteListener(ActionListener e) {
        this.btn_delete.addActionListener(e);
    }

    public void addUpdateListener(ActionListener e) {
        this.btn_update.addActionListener(e);
    }

    public void addEditListener(ActionListener e) {
        this.btn_edit.addActionListener(e);
    }

    public void addBackListener(ActionListener e) {
        this.btn_back.addActionListener(e);
    }

    public void buttonsave(boolean status) {
        this.btn_save.setEnabled(status);
    }

    public void buttonback(boolean status) {
        this.btn_back.setEnabled(status);
    }

    public void buttondelete(boolean status) {
        this.btn_delete.setEnabled(status);
    }

    public void buttonedit(boolean status) {
        this.btn_edit.setEnabled(status);
    }

    public void buttonupdate(boolean status) {
        this.btn_update.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_user = new javax.swing.JTable();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        namadepan = new javax.swing.JTextField();
        namabelakang = new javax.swing.JTextField();
        jenis_kelamin = new javax.swing.JComboBox();
        status = new javax.swing.JComboBox<>();
        email = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        kode_pos = new javax.swing.JTextField();
        no_telp = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Black Diamonds Personal Use", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pendaftaran");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 70));

        tb_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_user);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 590, -1));

        btn_save.setText("SAVE");
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, 90, 40));

        btn_edit.setText("EDIT");
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 90, 40));

        btn_update.setText("UPDATE");
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 590, 90, 40));

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 90, 40));

        btn_back.setText("KEMBALI");
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 150, 60));
        getContentPane().add(namadepan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 190, 30));

        namabelakang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabelakangActionPerformed(evt);
            }
        });
        getContentPane().add(namabelakang, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 190, 30));

        jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PILIH SALAH SATU", "Laki-laki", "Perempuan", " " }));
        getContentPane().add(jenis_kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 190, 30));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Isi", "Petani" }));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 190, 30));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 190, 30));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 190, 30));
        getContentPane().add(kode_pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 190, 30));
        getContentPane().add(no_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 190, 30));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 190, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID     :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 80, 60));

        id.setBackground(new java.awt.Color(204, 204, 204));
        id.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 74, 120, 50));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pendaftaran.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pendaftaran.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void namabelakangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namabelakangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabelakangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JTextField email;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jenis_kelamin;
    private javax.swing.JTextField kode_pos;
    private javax.swing.JTextField namabelakang;
    private javax.swing.JTextField namadepan;
    private javax.swing.JTextField no_telp;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable tb_user;
    // End of variables declaration//GEN-END:variables
}
