/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author InSearchOfIncredible
 */
public class penjadwalanBibit extends javax.swing.JFrame {

    /**
     * Creates new form penjadwalanBibit
     */
    public penjadwalanBibit() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JTable getTable() {
        return tb_jadwal;
    }

    public void addSimpanListener(ActionListener listener) {
        btn_save.addActionListener(listener);
    }

    public void addHapusListener(ActionListener listener) {
        btn_delete.addActionListener(listener);
    }

    public void backListener(ActionListener listener) {
        btn_kembali.addActionListener(listener);
    }

    public JDateChooser getTanggal() {
        return tanggal;
    }

    public JTextField getPetani() {
        return petani;
    }

    public JTextField getLuas() {
        return luas;
    }

    public JTextArea getAnalisa(String string) {
        return message;
    }

    public void setAnalisa(String text) {
        message.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        petani = new javax.swing.JTextField();
        luas = new javax.swing.JTextField();
        tanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_jadwal = new javax.swing.JTable();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Black Diamonds Personal Use", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Penjadwalan Bibit");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 450, 110));

        petani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        petani.setForeground(new java.awt.Color(255, 255, 255));
        petani.setBorder(null);
        petani.setOpaque(false);
        getContentPane().add(petani, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 220, 30));

        luas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luas.setForeground(new java.awt.Color(255, 255, 255));
        luas.setBorder(null);
        luas.setOpaque(false);
        getContentPane().add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 220, 30));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 220, 30));

        message.setColumns(20);
        message.setRows(5);
        jScrollPane1.setViewportView(message);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 290, 180));

        tb_jadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_jadwal);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 510, 190));

        btn_save.setText("SAVE");
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 80, 30));

        btn_delete.setText("DELETE");
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, 90, 30));

        btn_kembali.setText("KEMBALI");
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jadwal bibit.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjadwalanBibit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjadwalanBibit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjadwalanBibit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjadwalanBibit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjadwalanBibit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField luas;
    private javax.swing.JTextArea message;
    private javax.swing.JTextField petani;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTable tb_jadwal;
    // End of variables declaration//GEN-END:variables

}
